services:

  sample_go:
    image: template.utils/sample-go
    build: ./app/sample_go
    volumes:
      - ./app/sample_go/src:/app

  sample_py:
    image: template.utils/sample-py
    build: ./app/sample_py
    volumes:
      - ./app/sample_py/src:/app
