FROM mcr.microsoft.com/devcontainers/universal:2
ARG USERNAME=codespace
RUN apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
USER ${USERNAME}
